### ISSUE TITLE
Possible bug with seraph authenticator

### ISSUE THREAD

**Issue by straav** [allenta/gitlab-listener#12]
We have a custom authenticator, and we seem to be bing passed just null as the user.
The gitlab listener seems to have passed a username=null to seraph, and is not failing to the default user.

**Comment by carlosabalde** [comment]
Could you please describe how that custom authenticator works? Have you checked JIRA log?

**Comment by straav** [comment]
https://github.com/UW-Madison-DoIT/jiraRemoteUserAuth 
We have looked at the log, and looks like a null string is being passed.

**Comment by carlosabalde** [comment]
Could you execute and paste here the output of executing the following command (replacing `https://www.example.com/jira` by the root URL of your JIRA installation) in the server you're running GitLab?: `curl -v https://www.example.com/jira/plugins/servlet/gitlab/listener`

**Comment by straav** [comment]
- Hostname was NOT found in DNS cache
-   Trying ##.##.##.##...
- Connected to jira.edu.edu (##.##.##.##) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: none
  CApath: /etc/ssl/certs
- SSLv3, TLS handshake, Client hello (1):
- SSLv3, TLS handshake, Server hello (2):
- SSLv3, TLS handshake, CERT (11):
- SSLv3, TLS handshake, Server key exchange (12):
- SSLv3, TLS handshake, Server finished (14):
- SSLv3, TLS handshake, Client key exchange (16):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSL connection using ECDHE-RSA-AES128-GCM-SHA256
- Server certificate:
-    subject: C=US; postalCode=; ST=; L=; street= Street; O=University of; OU=OCIS; CN=jira.edu.edu
-    start date: 2013-10-25 00:00:00 GMT
-    expire date: 2016-10-24 23:59:59 GMT
-    subjectAltName: jira.edu.edu matched
-    issuer: C=US; O=Internet2; OU=InCommon; CN=InCommon Server CA
-    SSL certificate verify ok.
  > GET /jira/plugins/servlet/gitlab/listener HTTP/1.1
  > User-Agent: curl/7.35.0
  > Host: jira.edu.edu
  > Accept: _/_
  > 
  < HTTP/1.1 200 OK
  < Date: Wed, 29 Jul 2015 13:03:17 GMT
  < X-AREQUESTID: 483x2062x1
  < Set-Cookie: JSESSIONID=38C9EE8F7108E2A5A328F6D79C8F5AEC; Path=/jira; Secure
  < X-ASEN: SEN-183074
  < Set-Cookie: atlassian.xsrf.token=AOLF-WIIS-D2SP-8305|1e9fdeb3905ee4018c78bc7ef5e9e67ef6800f90|lout; Path=/jira; Secure
  < X-ASESSIONID: frr8bs
  < X-AUSERNAME: anonymous
  < X-Content-Type-Options: nosniff
  < Content-Type: text/html;charset=UTF-8
  < Transfer-Encoding: chunked
  < 
- Connection #0 to host jira.edu.edu left intact

**Comment by carlosabalde** [comment]
So, it seems the servlet providing the GitLab listener logic is reachable from the GitLab host. That's good.

Next check would be pushing one commit to a GitLab project with the GitLab Listener push webhook enabled while tailing the JIRA log and share here the exact messages logged by JIRA.

**Comment by straav** [comment]
2015-07-31 10:45:37,324 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] getUser: requestURL=https://jira-test/jira/plugins/servlet/gitlab/listener, remoteIP=gitlab-test, remoteHost=gitlab-test
2015-07-31 10:45:37,324 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Found the following HTTP headers:
    content-type="application/json"
    X-Gitlab-Event="Push Hook"
    connection="close"
    host="jira-test"
    content-length="975"
2015-07-31 10:45:37,324 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^(._)@edu$' did not match value=''
2015-07-31 10:45:37,324 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser1@edu$' did not match value=''
2015-07-31 10:45:37,324 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser12@edu$' did not match value=''
2015-07-31 10:45:37,324 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser13@edu$' did not match value=''
2015-07-31 10:45:37,324 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser14@uwec.edu$' did not match value=''
2015-07-31 10:45:37,324 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser15@edu$' did not match value=''
2015-07-31 10:45:37,324 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser16@edu$' did not match value=''
2015-07-31 10:45:37,328 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user is returned as is, mappers did not matched.
2015-07-31 10:45:37,328 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user was null or empty, can not perform authentication.
2015-07-31 10:45:37,328 TP-Processor12 DEBUG anonymous 645x320x1 - gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Login failed for user null. request=com.atlassian.seraph.filter.BaseLoginFilter$SecurityHttpRequestWrapper@39435032, username=null, remoteHost=gitlab-test, remoteIP=gitlab-test, reason=NoUsername
2015-07-31 10:45:37,330 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] getUser: requestURL=https://jira-test/jira/plugins/servlet/gitlab/listener, remoteIP=gitlab-test, remoteHost=gitlab-test
2015-07-31 10:45:37,330 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Found the following HTTP headers:
    content-type="application/json"
    X-Gitlab-Event="Push Hook"
    connection="close"
    host="jira-test"
    content-length="975"
2015-07-31 10:45:37,331 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^(._)@edu$' did not match value=''
2015-07-31 10:45:37,331 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser1@edu$' did not match value=''
2015-07-31 10:45:37,331 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser12@edu$' did not match value=''
2015-07-31 10:45:37,331 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser13@edu$' did not match value=''
2015-07-31 10:45:37,331 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser14@uwec.edu$' did not match value=''
2015-07-31 10:45:37,331 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser15@edu$' did not match value=''
2015-07-31 10:45:37,331 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser16@edu$' did not match value=''
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user is returned as is, mappers did not matched.
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user was null or empty, can not perform authentication.
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Login failed for user null. request=com.atlassian.plugin.servlet.PluginHttpRequestWrapper@2891d283, username=null, remoteHost=gitlab-test, remoteIP=gitlab-test, reason=NoUsername
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] getUser: requestURL=https://jira-test/jira/plugins/servlet/gitlab/listener, remoteIP=gitlab-test, remoteHost=gitlab-test
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Found the following HTTP headers:
    content-type="application/json"
    X-Gitlab-Event="Push Hook"
    connection="close"
    host="jira-test"
    content-length="975"
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^(.*)@edu$' did not match value=''
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser1@edu$' did not match value=''
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser12@edu$' did not match value=''
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser13@edu$' did not match value=''
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser14@uwec.edu$' did not match value=''
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser15@edu$' did not match value=''
2015-07-31 10:45:37,332 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser16@edu$' did not match value=''
2015-07-31 10:45:37,334 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user is returned as is, mappers did not matched.
2015-07-31 10:45:37,334 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user was null or empty, can not perform authentication.
2015-07-31 10:45:37,334 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Login failed for user null. request=com.atlassian.plugin.servlet.PluginHttpRequestWrapper@2891d283, username=null, remoteHost=gitlab-test, remoteIP=gitlab-test, reason=NoUsername
2015-07-31 10:45:37,356 TP-Processor12 ERROR anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [plugins.gitlab.listener.Servlet] Got unexpected exception while processing commit data.
com.atlassian.activeobjects.internal.ActiveObjectsInitException: bundle [com.allenta.jira.plugins.gitlab.gitlab-listener]
    at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:105)
    at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:92)
    at com.atlassian.sal.core.executor.ThreadLocalDelegateCallable.call(ThreadLocalDelegateCallable.java:42)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.atlassian.activeobjects.internal.ActiveObjectsSqlException: There was a SQL exception thrown by the Active Objects library:
Database:
    - name:Oracle
    - version:Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
    - minor version:2
    - major version:11
Driver:
    - name:Oracle JDBC driver
    - version:11.2.0.3.0

java.sql.SQLException: ORA-01408: such column list already indexed

```
at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.migrate(EntityManagedActiveObjects.java:54)
at com.atlassian.activeobjects.internal.AbstractActiveObjectsFactory$1.doInTransaction(AbstractActiveObjectsFactory.java:91)
at com.atlassian.activeobjects.internal.AbstractActiveObjectsFactory$1.doInTransaction(AbstractActiveObjectsFactory.java:85)
at com.atlassian.sal.core.transaction.HostContextTransactionTemplate$1.doInTransaction(HostContextTransactionTemplate.java:25)
at com.atlassian.jira.DefaultHostContextAccessor.doInTransaction(DefaultHostContextAccessor.java:34)
at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.atlassian.plugin.osgi.hostcomponents.impl.DefaultComponentRegistrar$ContextClassLoaderSettingInvocationHandler.invoke(DefaultComponentRegistrar.java:134)
at com.sun.proxy.$Proxy279.doInTransaction(Unknown Source)
at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.atlassian.plugin.osgi.bridge.external.HostComponentFactoryBean$DynamicServiceInvocationHandler.invoke(HostComponentFactoryBean.java:154)
at com.sun.proxy.$Proxy279.doInTransaction(Unknown Source)
at com.atlassian.sal.core.transaction.HostContextTransactionTemplate.execute(HostContextTransactionTemplate.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
at org.springframework.osgi.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:58)
at org.springframework.osgi.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:62)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
at org.springframework.osgi.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:56)
at org.springframework.osgi.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:39)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
at org.springframework.osgi.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:59)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
at com.sun.proxy.$Proxy1400.execute(Unknown Source)
at com.atlassian.activeobjects.internal.AbstractActiveObjectsFactory.create(AbstractActiveObjectsFactory.java:84)
at com.atlassian.activeobjects.internal.DelegatingActiveObjectsFactory.create(DelegatingActiveObjectsFactory.java:40)
at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:99)
... 6 more
```

Caused by: java.sql.SQLException: ORA-01408: such column list already indexed

```
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:193)
at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1033)
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1838)
at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1803)
at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:294)
at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
at net.java.ao.DatabaseProvider.executeUpdate(DatabaseProvider.java:2361)
at net.java.ao.DatabaseProvider.executeUpdateForAction(DatabaseProvider.java:2431)
at net.java.ao.DatabaseProvider.executeUpdatesForActions(DatabaseProvider.java:2394)
at net.java.ao.schema.SchemaGenerator.migrate(SchemaGenerator.java:98)
at net.java.ao.EntityManager.migrate(EntityManager.java:130)
at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.migrate(EntityManagedActiveObjects.java:50)
... 45 more
```

2015-07-31 10:45:37,357 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] getUser: requestURL=https://jira-test/jira/plugins/servlet/gitlab/listener, remoteIP=gitlab-test, remoteHost=gitlab-test
2015-07-31 10:45:37,357 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Found the following HTTP headers:
    content-type="application/json"
    X-Gitlab-Event="Push Hook"
    connection="close"
    host="jira-test"
    content-length="975"
2015-07-31 10:45:37,358 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^(._)@edu$' did not match value=''
2015-07-31 10:45:37,358 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser1@edu$' did not match value=''
2015-07-31 10:45:37,358 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser12@edu$' did not match value=''
2015-07-31 10:45:37,358 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser13@edu$' did not match value=''
2015-07-31 10:45:37,358 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser14@uwec.edu$' did not match value=''
2015-07-31 10:45:37,358 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser15@edu$' did not match value=''
2015-07-31 10:45:37,358 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser16@edu$' did not match value=''
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user is returned as is, mappers did not matched.
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user was null or empty, can not perform authentication.
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Login failed for user null. request=com.atlassian.plugin.servlet.PluginHttpRequestWrapper@2891d283, username=null, remoteHost=gitlab-test, remoteIP=gitlab-test, reason=NoUsername
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] getUser: requestURL=https://jira-test/jira/plugins/servlet/gitlab/listener, remoteIP=gitlab-test, remoteHost=gitlab-test
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Found the following HTTP headers:
    content-type="application/json"
    X-Gitlab-Event="Push Hook"
    connection="close"
    host="jira-test"
    content-length="975"
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^(._)@edu$' did not match value=''
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser1@edu$' did not match value=''
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser12@edu$' did not match value=''
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser13@edu$' did not match value=''
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser14@uwec.edu$' did not match value=''
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser15@edu$' did not match value=''
2015-07-31 10:45:37,361 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.GroupMapper] Regexp '^hardcodeduser16@edu$' did not match value=''
2015-07-31 10:45:37,364 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user is returned as is, mappers did not matched.
2015-07-31 10:45:37,364 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Remote user was null or empty, can not perform authentication.
2015-07-31 10:45:37,365 TP-Processor12 DEBUG anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [jira.authentication.shibboleth.RemoteUserAuthenticator] Login failed for user null. request=com.atlassian.plugin.servlet.PluginHttpRequestWrapper@2891d283, username=null, remoteHost=gitlab-test, remoteIP=gitlab-test, reason=NoUsername

**Comment by carlosabalde** [comment]
According with the log, it's now obvious for me that the problem is related with an incompatibility between the GitLab Listener and the Shibboleth Authenticator add-ons.

It seems that the webhook POST notification from GitLab reaches the GitLab Listener servlet, but a database exception is raised while processing the notification:

```
2015-07-31 10:45:37,356 TP-Processor12 ERROR anonymous 645x320x1 1jfj1kv gitlab-test /plugins/servlet/gitlab/listener [plugins.gitlab.listener.Servlet] Got unexpected exception while processing commit data.
com.atlassian.activeobjects.internal.ActiveObjectsInitException: bundle [com.allenta.jira.plugins.gitlab.gitlab-listener]
at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:105)
at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:92)
at com.atlassian.sal.core.executor.ThreadLocalDelegateCallable.call(ThreadLocalDelegateCallable.java:42)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.atlassian.activeobjects.internal.ActiveObjectsSqlException: There was a SQL exception thrown by the Active Objects library:
Database:
- name:Oracle
- version:Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
- minor version:2
- major version:11
Driver:
- name:Oracle JDBC driver
- version:11.2.0.3.0

java.sql.SQLException: ORA-01408: such column list already indexed
```

After some googling this seems related with Oracle and indexes already created. The best I can suggest is asking your DBA to look for indexes containing the word `COMMIT` (that's the name of the only persistent entity managed by the add-on) and rename or remove them. More about this [here](https://answers.atlassian.com/questions/229153/ora-01408-such-column-list-already-indexed).

**Comment by straav** [comment]
Looking into it, seems like the install is failing to create DB objects for the plugin. Can you share the SQL you use to make DB objects?

**Comment by carlosabalde** [comment]
There is not such a thing like explicit SQL queries I can share with you. The add-on uses the [Active Objects ORM](https://developer.atlassian.com/docs/atlassian-platform-common-components/active-objects) when accessing to the storage layer.

In any case, the storage requirements of the add-on are very simple. It only defines one entity named `Commit`, mapped by the ORM to some tables and indexes. According with Google, it seems that the problem you're experiencing is common when using Oracle as the underlying storage and it seems it can be fixed manually removing the indexes of the `Commit` table (which will be later recreated).

**Comment by carlosabalde** [comment]
Closing this issue due to inactivity in the last month.
