### ISSUE TITLE
Plugin broken

### ISSUE THREAD

**Issue by dMopp** [allenta/gitlab-listener#44]
The plugin is not wirking in our installation anymore, all we see is:

`2016-10-25 11:24:29,621 http-nio-8080-exec-35 ERROR anonymous 684x181285x1 - 10.53.1.44,10.20.0.101 /plugins/servlet/gitlab/listener [c.a.j.p.gitlab.listener.Servlet] Got unexpected exception while processing commit #0.
com.atlassian.activeobjects.internal.ActiveObjectsInitException: bundle [com.allenta.jira.plugins.gitlab.gitlab-listener]
        at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:95)
        at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:86)
        at com.atlassian.sal.core.executor.ThreadLocalDelegateCallable.call(ThreadLocalDelegateCallable.java:38)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.atlassian.activeobjects.internal.ActiveObjectsSqlException: There was a SQL exception thrown by the Active Objects library:
Database:
        - name:PostgreSQL
        - version:9.5.4
        - minor version:5
        - major version:9
        - name:PostgreSQL Native Driver
        - version:PostgreSQL 9.1 JDBC4 (build 903)
org.postgresql.util.PSQLException: ERROR: constraint "u_ao_9b0d9b_process1872808052" of relation "AO_9B0D9B_PROCESSED_COMMIT" does not exist
        at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.migrate(EntityManagedActiveObjects.java:53)
        at com.atlassian.activeobjects.internal.AbstractActiveObjectsFactory$1.doInTransaction(AbstractActiveObjectsFactory.java:77)
        at com.atlassian.activeobjects.internal.AbstractActiveObjectsFactory$1.doInTransaction(AbstractActiveObjectsFactory.java:72)
        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate$1.doInTransaction(HostContextTransactionTemplate.java:21)
        at com.atlassian.jira.DefaultHostContextAccessor.doInTransaction(DefaultHostContextAccessor.java:34)
        ... 2 filtered
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26)
        at com.sun.proxy.$Proxy106.doInTransaction(Unknown Source)
        ... 2 filtered
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.atlassian.plugin.osgi.bridge.external.HostComponentFactoryBean$DynamicServiceInvocationHandler.invoke(HostComponentFactoryBean.java:136)
        at com.sun.proxy.$Proxy106.doInTransaction(Unknown Source)
        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate.execute(HostContextTransactionTemplate.java:18)
        ... 2 filtered
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy944.execute(Unknown Source)
        at com.atlassian.activeobjects.internal.AbstractActiveObjectsFactory.create(AbstractActiveObjectsFactory.java:72)
        at com.atlassian.activeobjects.internal.DelegatingActiveObjectsFactory.create(DelegatingActiveObjectsFactory.java:32)
        at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:91)
        ... 6 more
Caused by: org.postgresql.util.PSQLException: ERROR: constraint "u_ao_9b0d9b_process1872808052" of relation "AO_9B0D9B_PROCESSED_COMMIT" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2101)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1834)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:510)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:372)
        at org.apache.commons.dbcp2.DelegatingStatement.executeUpdate(DelegatingStatement.java:234)
        at org.apache.commons.dbcp2.DelegatingStatement.executeUpdate(DelegatingStatement.java:234)
        at net.java.ao.DatabaseProvider.executeUpdate(DatabaseProvider.java:2238)
        at net.java.ao.DatabaseProvider.executeUpdateForAction(DatabaseProvider.java:2294)
        at net.java.ao.DatabaseProvider.executeUpdatesForActions(DatabaseProvider.java:2266)
        at net.java.ao.schema.SchemaGenerator.migrate(SchemaGenerator.java:91)
        at net.java.ao.EntityManager.migrate(EntityManager.java:128)
        at com.atlassian.activeobjects.internal.EntityManagedActiveObjects.migrate(EntityManagedActiveObjects.java:51)
        ... 44 more`

in catalina.out

any clue?

**Comment by carlosabalde** [comment]
I guess the problem is related with some kind of 'corruption' on the PostgreSQL storage:

```
There was a SQL exception thrown by the Active Objects library: Database: - name:PostgreSQL - version:9.5.4 - minor version:5 - major version:9 - name:PostgreSQL Native Driver - version:PostgreSQL 9.1 JDBC4 (build 903) org.postgresql.util.PSQLException: ERROR: constraint "u_ao_9b0d9b_process1872808052" of relation "AO_9B0D9B_PROCESSED_COMMIT" does not exist
```

`9B0D9B` is the internal ID of the add-on. I'm afraid my best suggestion here is try uninstalling - installing the add-on.

**Comment by dMopp** [comment]
uninstalling was not helping, we will try to manually rename/remove the table and install again, lets see

**Comment by dMopp** [comment]
ok, dropping the table AND reinstall solved the issue :) (reinstall only did not)
